"""change embedding dim to 384

Revision ID: 64bb721625c4
Revises: b82311e312f3
Create Date: 2026-04-21 15:13:29.005205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '64bb721625c4'
down_revision: Union[str, Sequence[str], None] = 'b82311e312f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('frequently_asked_questions', 'embedding',
               existing_type=Vector(1536),
               type_=Vector(384),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('frequently_asked_questions', 'embedding',
               existing_type=Vector(384),
               type_=Vector(1536),
               existing_nullable=True)
    # ### end Alembic commands ###
