"""added Feild tag

Revision ID: 8336c214b43f
Revises: 629a4e1f6688
Create Date: 2026-04-21 14:39:01.539621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8336c214b43f'
down_revision: Union[str, Sequence[str], None] = '629a4e1f6688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frequently_asked_questions', sa.Column('tag', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frequently_asked_questions', 'tag')
    # ### end Alembic commands ###
